# Generated by Django 5.0.7 on 2024-07-26 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('company_name', models.CharField(max_length=30)),
                ('company_employee_name', models.CharField(max_length=30)),
                ('company_contact', models.CharField(max_length=30)),
                ('employee_number', models.IntegerField()),
                ('lifetime', models.IntegerField()),
            ],
            options={
                'verbose_name': 'BotCompany',
                'verbose_name_plural': 'BotCompanies',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=30)),
                ('add_contact', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'BotUser',
                'verbose_name_plural': 'BotUsers',
            },
        ),
        migrations.CreateModel(
            name='BotCompanyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('bot_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_company', to='bot.botcompany')),
            ],
            options={
                'verbose_name': 'BotCompanyOrder',
                'verbose_name_plural': 'BotCompanyOrders',
            },
        ),
        migrations.CreateModel(
            name='BotUserOrder',
            fields=[
                ('botcompany_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.botcompany')),
                ('product_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('bot_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='bot.botuser')),
            ],
            options={
                'verbose_name': 'BotUserOrder',
                'verbose_name_plural': 'BotUserOrders',
            },
            bases=('bot.botcompany',),
        ),
    ]
