# Generated by Django 5.0.7 on 2024-08-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_botcompany_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcompany',
            name='language',
            field=models.CharField(choices=[('UZ', 'Uzbek'), ('RU', 'Russian')], default='UZ', max_length=2),
        ),
        migrations.AddField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('UZ', 'Uzbek'), ('RU', 'Russian')], default='UZ', max_length=2),
        ),
    ]
