# Generated by Django 5.0.7 on 2024-08-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botcompany_language_botuser_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botcompany',
            options={'ordering': ['-created_at'], 'verbose_name': 'BotCompany', 'verbose_name_plural': 'BotCompany'},
        ),
        migrations.AlterModelOptions(
            name='botcompanyorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'BotCompanyOrder', 'verbose_name_plural': 'BotCompanyOrders'},
        ),
        migrations.AlterModelOptions(
            name='botuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'BotUser', 'verbose_name_plural': 'BotUsers'},
        ),
        migrations.RemoveField(
            model_name='botcompany',
            name='company_employee_name_en',
        ),
        migrations.RemoveField(
            model_name='botcompany',
            name='company_name_en',
        ),
        migrations.RemoveField(
            model_name='botcompanyorder',
            name='product_name_en',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='name_en',
        ),
    ]
