# Generated by Django 5.0.7 on 2024-08-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_botcompany_language_remove_botuser_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botcompany',
            options={'ordering': ['-created_at'], 'verbose_name': 'BotCompany', 'verbose_name_plural': 'BotCompanies'},
        ),
        migrations.AddField(
            model_name='botcompany',
            name='is_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
