# Generated by Django 5.0.7 on 2024-07-31 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_botcompany_options_and_more'),
        ('webapp', '0003_remove_product_description_af_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='bot_company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_order', to='bot.botcompany'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='bot_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_order', to='bot.botuser'),
        ),
    ]
