# Generated by Django 5.0.7 on 2024-08-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_cartitem_bot_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='title_en',
        ),
    ]
