# Generated by Django 5.0.7 on 2024-08-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_product_description_en_remove_product_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='shares',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shares', 'verbose_name_plural': 'Shares'},
        ),
    ]
