# Generated by Django 5.0.7 on 2024-08-19 05:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_cartitem_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
